source 'http://rubygems.org'

gem 'admin_data'
gem 'aws-s3'
gem 'dalli'
gem 'delayed_job'
gem 'devise'
gem 'domainatrix'
gem 'geokit-rails3'
gem 'goalie'
gem 'formtastic', '1.2.2'
gem 'friendly_id'
gem 'hoptoad_notifier'
gem 'mechanize'
gem 'mysql2'
gem 'PageRankr'
gem 'paperclip'
gem 'pismo'
gem 'rails', '3.0.3'
gem 'settingslogic'
gem 'will_paginate', '3.0.pre2'
gem 'whois', '2.0.1'

group :development, :test do
  gem 'factory_girl_rails'
  gem 'autotest'
  gem 'haml'
  gem 'mocha'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'ruby-debug19'
  gem 'shoulda-matchers'

  #gem "factory_girl", "2.0.0.beta1"
end