defaults: &defaults
  root_url: "https://www.lineofthought.com"
  root_domain: "www.lineofthought.com"
  root_image_url: "https://s3.amazonaws.com/s.lineofthought.com"

development:
 <<: *defaults
 root_domain: "lineofthought.local:3000"
 root_url: "http://lineofthought.local:3000"

test:
 <<: *defaults

production:
 <<: *defaults