--- 
javascripts: 
- all: 
  - jquery/jquery.tokeninput
  - jquery/autoresize.jquery.min
  - rails
  - handlebars-0.9.0.pre.4
  - application
stylesheets: 
- all: 
  - flutie
  - tokeninput
  - layout
  - style
  - forms
  - new-list
  - smoothness/jquery-ui-1.8.11.custom